import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import '../lib/polyfills';
import { cookies } from "next/headers";
import { redirect } from "next/navigation";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
// const cookieStore = await cookies(); // 🔥 FIX
//   const token = cookieStore.get("auth_token")?.value;
//   if (!token) {
//     redirect("/login");
//   }

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`} suppressHydrationWarning>
        {children}
      </body>
    </html>
  );
}
